name: MammaNell
favicon: null
layout_spectrum: 0.06125011295080185
typography_spectrum: 0.1981600821018219
title: 'Licensed Massage Therapist & Essential Oil Blendologist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.47514648572541773
  lightness: 0.19506549183279276
  saturation: 0.43162188003771007
  rhythmicContrast: 0.33708810806274414
purpose: []
